[book]
authors = ["Nursan Valeyev"]
language = "en"
multilingual = false
src = "src"
title = "C++ Course"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/CPP-KT/course"
mathjax-support = true
